# Cloud Build configuration for Polkassembly V2
# This file configures the build process including secret management and deployment

steps:
  # Build the container image with all required secrets as build arguments
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg NEXT_PUBLIC_APP_ENV="$$NEXT_PUBLIC_APP_ENV" \
          --build-arg NEXT_PUBLIC_DEFAULT_NETWORK="$$NEXT_PUBLIC_DEFAULT_NETWORK" \
          --build-arg FIREBASE_SERVICE_ACC_CONFIG="$$FIREBASE_SERVICE_ACC_CONFIG" \
          --build-arg REDIS_URL="$$REDIS_URL" \
          --build-arg ACCESS_TOKEN_PRIVATE_KEY="$$ACCESS_TOKEN_PRIVATE_KEY" \
          --build-arg ACCESS_TOKEN_PUBLIC_KEY="$$ACCESS_TOKEN_PUBLIC_KEY" \
          --build-arg ACCESS_TOKEN_PASSPHRASE="$$ACCESS_TOKEN_PASSPHRASE" \
          --build-arg REFRESH_TOKEN_PRIVATE_KEY="$$REFRESH_TOKEN_PRIVATE_KEY" \
          --build-arg REFRESH_TOKEN_PUBLIC_KEY="$$REFRESH_TOKEN_PUBLIC_KEY" \
          --build-arg REFRESH_TOKEN_PASSPHRASE="$$REFRESH_TOKEN_PASSPHRASE" \
          --build-arg NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY="$$NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY" \
          --build-arg NEXT_PUBLIC_ALGOLIA_APP_ID="$$NEXT_PUBLIC_ALGOLIA_APP_ID" \
          --build-arg SUBSCAN_API_KEY="$$SUBSCAN_API_KEY" \
          --build-arg IS_CACHE_ENABLED="$$IS_CACHE_ENABLED" \
          --build-arg IS_AI_ENABLED="$$IS_AI_ENABLED" \
          --build-arg IS_NOTIFICATION_SERVICE_ENABLED="$$IS_NOTIFICATION_SERVICE_ENABLED" \
          --build-arg AI_SERVICE_URL="$$AI_SERVICE_URL" \
          --build-arg TOOLS_PASSPHRASE="$$TOOLS_PASSPHRASE" \
          --build-arg NOTIFICATION_ENGINE_API_KEY="$$NOTIFICATION_ENGINE_API_KEY" \
          --build-arg NEXT_PUBLIC_IMBB_KEY="$$NEXT_PUBLIC_IMBB_KEY" \
          --build-arg NEXT_PUBLIC_POLKASSEMBLY_API_KEY="$$NEXT_PUBLIC_POLKASSEMBLY_API_KEY" \
          --build-arg ALGOLIA_WRITE_API_KEY="$$ALGOLIA_WRITE_API_KEY" \
          --build-arg NEXT_PUBLIC_GA_ID="$$NEXT_PUBLIC_GA_ID" \
          -t gcr.io/$PROJECT_ID/polkassembly-v2-next-app:$COMMIT_SHA \
          -t gcr.io/$PROJECT_ID/polkassembly-v2-next-app:latest \
          .
    secretEnv:
      - 'NEXT_PUBLIC_APP_ENV'
      - 'NEXT_PUBLIC_DEFAULT_NETWORK'
      - 'FIREBASE_SERVICE_ACC_CONFIG'
      - 'REDIS_URL'
      - 'ACCESS_TOKEN_PRIVATE_KEY'
      - 'ACCESS_TOKEN_PUBLIC_KEY'
      - 'ACCESS_TOKEN_PASSPHRASE'
      - 'REFRESH_TOKEN_PRIVATE_KEY'
      - 'REFRESH_TOKEN_PUBLIC_KEY'
      - 'REFRESH_TOKEN_PASSPHRASE'
      - 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY'
      - 'NEXT_PUBLIC_ALGOLIA_APP_ID'
      - 'SUBSCAN_API_KEY'
      - 'IS_CACHE_ENABLED'
      - 'IS_AI_ENABLED'
      - 'IS_NOTIFICATION_SERVICE_ENABLED'
      - 'AI_SERVICE_URL'
      - 'TOOLS_PASSPHRASE'
      - 'NOTIFICATION_ENGINE_API_KEY'
      - 'NEXT_PUBLIC_IMBB_KEY'
      - 'NEXT_PUBLIC_POLKASSEMBLY_API_KEY'
      - 'ALGOLIA_WRITE_API_KEY'
      - 'NEXT_PUBLIC_GA_ID'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/polkassembly-v2-next-app'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'polkassembly-v2-next-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/polkassembly-v2-next-app:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--update-secrets'
      - 'KLARA_API_BASE_URL=KLARA_API_BASE_URL:latest,KLARA_POSTGRES_HOST=KLARA_POSTGRES_HOST:latest,KLARA_POSTGRES_PORT=KLARA_POSTGRES_PORT:latest,KLARA_POSTGRES_USER=KLARA_POSTGRES_USER:latest,KLARA_POSTGRES_PASSWORD=KLARA_POSTGRES_PASSWORD:latest,KLARA_POSTGRES_SSL=KLARA_POSTGRES_SSL:latest,KLARA_AI_TOKEN=KLARA_AI_TOKEN:latest,ALGOLIA_WRITE_API_KEY=ALGOLIA_WRITE_API_KEY:latest,NEXT_PUBLIC_DEFAULT_NETWORK=NEXT_PUBLIC_DEFAULT_NETWORK:latest,AI_SERVICE_URL=AI_SERVICE_URL:latest,IS_CACHE_ENABLED=IS_CACHE_ENABLED:latest,NEXT_PUBLIC_GA_ID=NEXT_PUBLIC_GA_ID:latest,SENTRY_AUTH_TOKEN=SENTRY_AUTH_TOKEN:latest,IS_AI_ENABLED=IS_AI_ENABLED:latest,IS_NOTIFICATION_SERVICE_ENABLED=IS_NOTIFICATION_SERVICE_ENABLED:latest,NOTIFICATION_ENGINE_API_KEY=NOTIFICATION_ENGINE_API_KEY:latest,SUBSCAN_API_KEY=SUBSCAN_API_KEY:latest,FIREBASE_SERVICE_ACC_CONFIG=FIREBASE_SERVICE_ACC_CONFIG:latest,TWITTER_CONSUMER_API_SECRET_KEY=TWITTER_CONSUMER_API_SECRET_KEY:latest,TWITTER_CONSUMER_API_KEY=TWITTER_CONSUMER_API_KEY:latest,VERIFICATION_CALLBACK_URL=VERIFICATION_CALLBACK_URL:latest,IDENTITY_JUDGEMENT_AUTH=IDENTITY_JUDGEMENT_AUTH:latest,REQUEST_JUDGEMENT_CF_URL=REQUEST_JUDGEMENT_CF_URL:latest,NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY=NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY:latest,NEXT_PUBLIC_ALGOLIA_APP_ID=NEXT_PUBLIC_ALGOLIA_APP_ID:latest,NEXT_PUBLIC_POLKASSEMBLY_API_KEY=NEXT_PUBLIC_POLKASSEMBLY_API_KEY:latest,TOOLS_PASSPHRASE=TOOLS_PASSPHRASE:latest,REDIS_URL=REDIS_URL:latest,NEXT_PUBLIC_IMBB_KEY=NEXT_PUBLIC_IMBB_KEY:latest,ACCESS_TOKEN_PASSPHRASE=ACCESS_TOKEN_PASSPHRASE:latest,ACCESS_TOKEN_PUBLIC_KEY=ACCESS_TOKEN_PUBLIC_KEY:latest,ACCESS_TOKEN_PRIVATE_KEY=ACCESS_TOKEN_PRIVATE_KEY:latest,NEXT_PUBLIC_APP_ENV=NEXT_PUBLIC_APP_ENV:latest,REFRESH_TOKEN_PRIVATE_KEY=REFRESH_TOKEN_PRIVATE_KEY:latest,REFRESH_TOKEN_PUBLIC_KEY=REFRESH_TOKEN_PUBLIC_KEY:latest,REFRESH_TOKEN_PASSPHRASE=REFRESH_TOKEN_PASSPHRASE:latest'

# Map secrets from Google Secret Manager to environment variables
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_APP_ENV/versions/latest
      env: 'NEXT_PUBLIC_APP_ENV'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_DEFAULT_NETWORK/versions/latest
      env: 'NEXT_PUBLIC_DEFAULT_NETWORK'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_SERVICE_ACC_CONFIG/versions/latest
      env: 'FIREBASE_SERVICE_ACC_CONFIG'
    - versionName: projects/$PROJECT_ID/secrets/REDIS_URL/versions/latest
      env: 'REDIS_URL'
    - versionName: projects/$PROJECT_ID/secrets/ACCESS_TOKEN_PRIVATE_KEY/versions/latest
      env: 'ACCESS_TOKEN_PRIVATE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/ACCESS_TOKEN_PUBLIC_KEY/versions/latest
      env: 'ACCESS_TOKEN_PUBLIC_KEY'
    - versionName: projects/$PROJECT_ID/secrets/ACCESS_TOKEN_PASSPHRASE/versions/latest
      env: 'ACCESS_TOKEN_PASSPHRASE'
    - versionName: projects/$PROJECT_ID/secrets/REFRESH_TOKEN_PRIVATE_KEY/versions/latest
      env: 'REFRESH_TOKEN_PRIVATE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/REFRESH_TOKEN_PUBLIC_KEY/versions/latest
      env: 'REFRESH_TOKEN_PUBLIC_KEY'
    - versionName: projects/$PROJECT_ID/secrets/REFRESH_TOKEN_PASSPHRASE/versions/latest
      env: 'REFRESH_TOKEN_PASSPHRASE'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_ALGOLIA_SEARCH_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_ALGOLIA_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_ALGOLIA_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/SUBSCAN_API_KEY/versions/latest
      env: 'SUBSCAN_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/IS_CACHE_ENABLED/versions/latest
      env: 'IS_CACHE_ENABLED'
    - versionName: projects/$PROJECT_ID/secrets/IS_AI_ENABLED/versions/latest
      env: 'IS_AI_ENABLED'
    - versionName: projects/$PROJECT_ID/secrets/IS_NOTIFICATION_SERVICE_ENABLED/versions/latest
      env: 'IS_NOTIFICATION_SERVICE_ENABLED'
    - versionName: projects/$PROJECT_ID/secrets/AI_SERVICE_URL/versions/latest
      env: 'AI_SERVICE_URL'
    - versionName: projects/$PROJECT_ID/secrets/TOOLS_PASSPHRASE/versions/latest
      env: 'TOOLS_PASSPHRASE'
    - versionName: projects/$PROJECT_ID/secrets/NOTIFICATION_ENGINE_API_KEY/versions/latest
      env: 'NOTIFICATION_ENGINE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_IMBB_KEY/versions/latest
      env: 'NEXT_PUBLIC_IMBB_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_POLKASSEMBLY_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_POLKASSEMBLY_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/ALGOLIA_WRITE_API_KEY/versions/latest
      env: 'ALGOLIA_WRITE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_GA_ID/versions/latest
      env: 'NEXT_PUBLIC_GA_ID'

# Build configuration options
options:
  # Use a more powerful machine for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Use Cloud Logging for better log management
  logging: CLOUD_LOGGING_ONLY

# Set a 1 hour timeout for the entire build process
timeout: '3600s'

