// Copyright 2019-2025 @polkassembly/polkassembly authors & contributors
// This software may be modified and distributed under the terms
// of the Apache-2.0 license. See the LICENSE file for details.

export const THEME_COLORS = {
	light: {
		wallet_btn_text: '#485F7D',
		bg_modal: '#FFF',
		navbar_border: '#E5007A',
		bg_pink: '#E5007A',
		btn_primary_background: '#E5007A',
		primary_border: '#D2D8E0',
		tooltip_background: '#363636',
		tooltip_foreground: '#FFFFFF',
		link: '#1B61FF',
		btn_primary_text: '#FFF',
		btn_secondary_border: '#D2D8E0',
		btn_secondary_background: '#FFF',
		btn_secondary_text: '#243A57',
		border_grey: '#D2D8E0',
		text_primary: '#243A57',
		text_pink: '#E5007A',
		placeholder: '#576D8BCC',
		success: '#2ED47A',
		failure: '#FF3C5F',
		text_grey: '#7587A0',
		sidebar_head1: '#F3F9D7',
		sidebar_head2: '#fdf8e1',
		sidebar_head3: '#ffede5',
		sidebar_head4: '#dff4ff',
		sidebar_footer: '#F3F4F6',
		sidebar_text: '#485F7D',
		sidebar_menu_text: '#ff0080',
		sidebar_menu_bg: '#fce6f1',
		create_proposal_btn_create: '#0A3EAF'
	},
	dark: {
		wallet_btn_text: '#485F7D',
		bg_modal: '#000',
		navbar_border: '#E5007A',
		bg_pink: '#E5007A',
		btn_primary_background: '#E5007A',
		primary_border: '#3F3F46',
		tooltip_background: '#363636',
		tooltip_foreground: '#FFFFFF',
		link: '#1B61FF',
		btn_primary_text: '#FFF',
		btn_secondary_border: '#D2D8E0',
		btn_secondary_background: '#FFF',
		btn_secondary_text: '#243A57',
		border_grey: '#D2D8E0',
		text_primary: '#FFF',
		text_pink: '#E5007A',
		placeholder: '#576D8BCC',
		success: '#2ED47A',
		failure: '#FF3C5F',
		text_grey: '#7587A0',
		create_proposal_btn_create: '#49CFFC'
	}
};
